// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AuthToken = { auth_token: string, };

export type BaseResponse = { ret: number, msg: string, };

export type LiveKitEgressInfo = { egress_id: string, };

export type LiveKitToken = { livekit_token: string, };
