// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LiveKitEgressInfo } from "./base";
import type { LiveKitToken } from "./base";

export type CreateRoomReq = { start_time: number, end_time: number, users_ids: Array<string>, };

export type LiveKitEgressInfoRes = { data: LiveKitEgressInfo | null, ret: number, msg: string, };

export type RoomListRes = { data: Array<RoomNode> | null, ret: number, msg: string, };

export type RoomNode = { id: number, code: string, is_canceled: boolean, start_time: number, end_time: number, admin: string, users_ids: Array<string>, };

export type RoomTokenRes = { data: LiveKitToken | null, ret: number, msg: string, };

export type UpdateRoomReq = { start_time: number | null, end_time: number | null, admin: string | null, is_canceled: boolean | null, user_ids: Array<string> | null, };
