// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthToken } from "./base";

export type UserLoginRes = { data: AuthToken | null, ret: number, msg: string, };

export type UserUpdateReq = { old_password: string, new_password: string, };
