[package]
name = "server-actix"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = { version = "4", features = [ "openssl" ] }
dotenv = "0.15.0"
serde = { version = "1.0", features = [ "derive" ] }
sea-orm = { version = "1.1.0", features = [
  "sqlx-sqlite",
  "runtime-tokio-native-tls",
  "macros"
] }
openssl = { version = "0.10" }
futures-util = "0.3.31"
jsonwebtoken = { version = "9.3.0", default-features = false }
actix-web-httpauth = "0.8.2"
log = "0.4.25"
env_logger = "0.11.6"
livekit-api = { version = "0.4.2", features = ["signal-client-async"]}
password-auth = "1.0.0"
rand = "0.9.0"
ts-rs = "10.1.0"
actix-cors = "0.7.1"
livekit-protocol = "0.3.9"
reqwest = { version = "0.12.15", features = ["json"] }
serde_json = "1.0.140"
