[package]
name = "server-actix"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = { version = "4", features = ["openssl"] }
dotenv = "0.15.0"
serde = { version = "1.0", features = ["derive"] }
sea-orm = { version = "1.1.0", features = [ "sqlx-sqlite", "runtime-tokio-native-tls", "macros" ] }
openssl = { version = "0.10" }
